homeassistant:
  # Name of the location where Home Assistant is running
  name: Cellerica
  # Location required to calculate the time the sun rises and sets
  latitude: 41.970729093815905
  longitude: 2.623243670005552
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 169
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid

  auth_providers:
    - type: homeassistant

default_config:

http:
  ip_ban_enabled: false
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.1.0.0/16
