apiVersion: v1
kind: l
metadata:
  name: homeassist-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  local:
    path: /data/homeassist
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: microk8s.io/cluster
          operator: In
          values:
          - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassist-pv-claim
  labels:
    app: homeassist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: homeassist-pv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassist-config
data:
  configuration: |
    homeassistant:
      # Name of the location where Home Assistant is running
      name: Cellerica
      # Location required to calculate the time the sun rises and sets
      latitude: 41.970729093815905
      longitude: 2.623243670005552
      # Impacts weather/sunrise data (altitude above sea level in meters)
      elevation: 169
      # metric for Metric, imperial for Imperial
      unit_system: metric
      time_zone: Europe/Madrid

      auth_providers:
        - type: homeassistant

    default_config:

    http:
      ip_ban_enabled: false
      login_attempts_threshold: 5
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.1.0.0/16
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassist-deployment
  labels:
    app: homeassist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassist
  template:
    metadata:
      labels:
        app: homeassist
    spec:
      containers:
        - name: homeassist
          image: homeassistant/home-assistant
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: "/config"
              name: homeassist-persistent-storage
            - mountPath: "/config/configuration.yaml"
              subPath: "configuration"
              name: homeassist-config-volume
      volumes:
        - name: homeassist-config-volume
          configMap:
            name: homeassist-config
        - name: homeassist-persistent-storage
          persistentVolumeClaim:
            claimName: homeassist-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: homeassist
spec:
  type: ClusterIP
  selector:
    app: homeassist
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8123

---
apiVersion: v1
kind: Service
metadata:
  name: homeassist-ingress-tcp
  namespace: ingress
  annotations:
    metallb.universe.tf/allow-shared-ip: "homeassist-shared-ip"
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  # loadBalancerIP is optional. MetalLB will automatically allocate an IP
  # from its pool if not specified. You can also specify one manually.
  loadBalancerIP: 192.168.31.10
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassist-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - homeassist.local.digitalpoet.info
      secretName: tls-local.digitalpoet.info
  rules:
    - host: homeassist.local.digitalpoet.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeassist
                port:
                  number: 443
