---
apiVersion: v1
kind: Secret
metadata:
  name: common.jwt.user.secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: secret
    secret-generator.v1.mittwald.de/encoding: hex
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: common.jwt.service.secret
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: secret
    secret-generator.v1.mittwald.de/encoding: hex
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: auth.mongodb.url
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/hook: Skip
type: Opaque
data:
  url: ""