apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_MONGODB_AUTH_DATABASE
              value: admin
            - name: ME_CONFIG_MONGODB_AUTH_USERNAME
              value: admin
            - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-rs-main-admin-admin
                  key: password
            - name: ME_CONFIG_MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-rs-main-admin-admin
                  key: connectionString.standard

---
apiVersion: v1
kind: Service
metadata:
  name: express-app
spec:
  type: ClusterIP
  selector:
    app: express-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: express-tcp
  namespace: ingress
  annotations:
    # metallb.universe.tf/loadBalancerIPs: 192.168.31.11
    # metallb.universe.tf/allow-shared-ip: "homeassist-shared-ip"
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  # loadBalancerIP is optional. MetalLB will automatically allocate an IP
  # from its pool if not specified. You can also specify one manually.
  loadBalancerIP: 192.168.31.12
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - express.local.digitalpoet.info
      secretName: tls-local.digitalpoet.info
  rules:
    - host: express.local.digitalpoet.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: express-app
                port:
                  number: 443
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-local.digitalpoet.info
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""