---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb.mongodb-main.admin
  namespace: mongodb
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb.mongodb-main.auth
  namespace: mongodb
type: Opaque